sudo: false

language: python

python:
  - "3.5"
  - "3.6"

env:
  - DJANGO="Django>=1.11,<2.0"
  - DJANGO="Django>=2.0,<2.1"

install:
  - nvm install 7
  - pip install git+https://github.com/django/daphne@2.0
  - pip install -U pip wheel setuptools flake8 isort unify
  - pip install $DJANGO -e .[tests]
  - pip freeze

script:
  - pytest
  - flake8
  - isort --check-only --recursive channels tests
  - unify --check-only --recursive --quote \" channels
#  - cd js_client && npm install --progress=false && npm test && cd ..
