dist: xenial

language: python

python:
  - "3.6"
  - "3.5"

env:
  - DJANGO="Django==1.11.*"
  - DJANGO="Django==2.1.*"
  - DJANGO="Django==2.2.*"

install:
  - pip install -U pip wheel setuptools
  - pip install $DJANGO -e .[tests]
  - pip freeze

script:
  - pytest

stages:
  - test
  - lint
  - name: release
    if: tag IS present

jobs:
  include:
    - python: "3.7"
      env: DJANGO="Django==2.1.*"
    - python: "3.7"
      env: DJANGO="Django==2.2.*"
    - python: "3.8"
      env: DJANGO="Django==2.2.*"

    - stage: lint
      install: pip install -U -e .[tests] black pyflakes isort
      script:
        - pyflakes channels tests
        - black --check --diff channels tests
        - isort --check-only --diff --recursive channels tests

    - stage: release
      script: skip
      deploy:
        provider: pypi
        user: andrewgodwin_bot
        on:
          tags: true
        distributions: sdist bdist_wheel
        password:
          secure: JQrDaSHhyrQZE4FFzGF2WDWIVlZOXP9xoGtrXSaSp+neWpr2a83UmAjEQYGFLX5aXvVBpaILL5fOfMnbnIBzArEC01RTTWm1iDuQkpvYU6DgbTsLnCl5g9V+Z3G+8tGSy3lGhFiViLBIi5Xi6PrwlBeK/LW1b9Ja8jsZdLWYHloFtyy5HkYodFOxYdpiXLeva9YXWKPnU9lKLLrubcRtbnvyAn9WY2Wn09Cy/6xcGqX0lPebf3gaXYMFQ9thDoZPgSqrxYYK57LA0EdMjSyxrs5GVGSVoNhnsAJn6JFzHwvGeuzjs/92bNUAcTM+oe6cZWHPiECgINKNFLTxH9x0sNanw2walNnw+9X9caqYnzrReiwKJoTiXd3fZSgFV5WplVMARw9kSvSnNclzTiToTNXrRmL5ATMgv5qixRctoDRaYgz/6i1mGt7ey5qyq0qEViBb9hB2NBwF3kVbJG8evdXqw8bcBQ1OCfXKLV0cWvRpdbjZ6hdCcJPgptztyGnlGwX8/eeAxrCYkQy8FmOmEV8c00mMUaoRfDqXxtqyii2UdwRL10Du6V47jjYxCGXN5bfMGXVi/xNdmw1gbZx5fhf5rMhGvux9mxGZVtU4Q7I5jEhQ/H+IwaoEjUA7e5qDfWB+hqMhnsineQb12ZZ//iKVo2x2eTTn6yJ0hVn8QP4=
