[build-system]
requires = ['setuptools>=40.8.0']
build-backend = 'setuptools.build_meta'

[tool.black]
target-version = ['py310']
force-exclude = 'tests/test_runner_apps/tagged/tests_syntax_error.py'

[tool.isort]
profile = 'black'
default_section = 'THIRDPARTY'
known_first_party = 'django'
