name: Docs

on:
  pull_request:
    paths:
      - 'docs/**'
      - '.github/workflows/docs.yml'
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - '.github/workflows/docs.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  docs:
    runs-on: ubuntu-24.04
    name: spelling
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          persist-credentials: false
      - name: Set up Python
        uses: actions/setup-python@v6
        id: setup_python
        with:
          python-version: '3.14'
      - name: Restore cached virtualenv
        uses: actions/cache/restore@v4
        with:
          key: venv-${{ runner.os }}-${{ steps.setup_python.outputs.python-version }}-${{ hashFiles('docs/requirements.txt') }}
          path: .venv
      - name: Install dependencies
        run: |
          if [ ! -d .venv ]; then
            python -m venv .venv
          fi
          source .venv/bin/activate
          python -m pip install -r docs/requirements.txt
          echo "$VIRTUAL_ENV/bin" >> $GITHUB_PATH
          echo "VIRTUAL_ENV=$VIRTUAL_ENV" >> $GITHUB_ENV
      - name: Save cached virtualenv
        uses: actions/cache/save@v4
        with:
          key: venv-${{ runner.os }}-${{ steps.setup_python.outputs.python-version }}-${{ hashFiles('docs/requirements.txt') }}
          path: .venv
      - name: Build docs
        run: |
          cd docs
          sphinx-build -b spelling -n -q -W -d _build/doctrees -D language=en_US -j auto . _build/spelling

  blacken-docs:
    runs-on: ubuntu-latest
    name: blacken-docs
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          persist-credentials: false
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.14'
      - run: python -m pip install blacken-docs
      - name: Build docs
        run: |
          cd docs
          make black
          RESULT=`cat _build/black/output.txt`
          if [ "$RESULT" -gt 0 ]; then
              echo "ðŸ’¥ ðŸ“¢ Code blocks in documentation must be reformatted with blacken-docs ðŸ“¢ ðŸ’¥"
          fi;
          exit $RESULT

  lint-docs:
    runs-on: ubuntu-latest
    name: lint-docs
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          persist-credentials: false
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.14'
      - run: python -m pip install sphinx-lint
      - name: Build docs
        run: |
          cd docs
          make lint
